//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub board_id: i32,
    pub name: String,
    pub color: String,
    pub position: i32,
    pub is_done: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Boards,
    #[sea_orm(has_many = "super::todos::Entity")]
    Todos,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
