//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub board_id: i32,
    pub is_group: bool,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Boards,
    #[sea_orm(has_many = "super::conversation_members::Entity")]
    ConversationMembers,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl Related<super::conversation_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMembers.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::conversation_members::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::conversation_members::Relation::Conversations
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
