//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "labels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub board_id: i32,
    pub name: String,
    pub color: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Boards,
    #[sea_orm(has_many = "super::todo_labels::Entity")]
    TodoLabels,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl Related<super::todo_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodoLabels.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        super::todo_labels::Relation::Todos.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::todo_labels::Relation::Labels.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
