//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub avatar_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::board_members::Entity")]
    BoardMembers,
    #[sea_orm(has_many = "super::boards::Entity")]
    Boards,
    #[sea_orm(has_many = "super::conversation_members::Entity")]
    ConversationMembers,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::todos::Entity")]
    Todos,
}

impl Related<super::board_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoardMembers.def()
    }
}

impl Related<super::conversation_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMembers.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todos.def()
    }
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        super::board_members::Relation::Boards.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::board_members::Relation::Users.def().rev())
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        super::conversation_members::Relation::Conversations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::conversation_members::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
